# Data files (too large for git / user-specific)
data/*.csv
data/*.xlsx
!data/.gitkeep

# Output files (regenerated by scripts)
output/*.png
output/*.csv
output/*.txt
output/*.pdf
!output/.gitkeep

# R environment
.Rhistory
.Rdata
.RData
.Rproj.user/
*.Rproj

# OS files
.DS_Store
Thumbs.db
